import type { ITask } from "@meu-projeto/types"

export const MOCK_TASKS: ITask[] = [
  {
    id: "1",
    title: "Criar wireframes do dashboard",
    description: "Desenhar os wireframes iniciais para o layout do dashboard principal",
    status: "in_progress",
    priority: "high",
    dueDate: new Date("2026-07-10"),
    timeEstimateMinutes: 120,
    assigneeId: null,
    milestoneId: null,
    parentId: null,
    orgId: null,
    createdAt: new Date("2026-07-01"),
    updatedAt: new Date("2026-07-03"),
  },
  {
    id: "2",
    title: "Configurar autenticação OAuth",
    description: "Integrar Google OAuth com better-auth",
    status: "todo",
    priority: "urgent",
    dueDate: new Date("2026-07-08"),
    timeEstimateMinutes: 180,
    assigneeId: null,
    milestoneId: null,
    parentId: null,
    orgId: null,
    createdAt: new Date("2026-07-02"),
    updatedAt: new Date("2026-07-02"),
  },
  {
    id: "3",
    title: "Escrever testes do backend",
    description: "Testes unitários para task service e controllers",
    status: "todo",
    priority: "medium",
    dueDate: new Date("2026-07-15"),
    timeEstimateMinutes: 240,
    assigneeId: null,
    milestoneId: null,
    parentId: null,
    orgId: null,
    createdAt: new Date("2026-07-03"),
    updatedAt: new Date("2026-07-03"),
  },
  {
    id: "4",
    title: "Documentar API endpoints",
    description: null,
    status: "done",
    priority: "low",
    dueDate: new Date("2026-07-05"),
    timeEstimateMinutes: 60,
    assigneeId: null,
    milestoneId: null,
    parentId: null,
    orgId: null,
    createdAt: new Date("2026-06-28"),
    updatedAt: new Date("2026-07-04"),
  },
  {
    id: "5",
    title: "Implementar WebSocket realtime",
    description: "Configurar ws para atualizações em tempo real das tasks",
    status: "todo",
    priority: "high",
    dueDate: new Date("2026-07-12"),
    timeEstimateMinutes: 300,
    assigneeId: null,
    milestoneId: null,
    parentId: null,
    orgId: null,
    createdAt: new Date("2026-07-04"),
    updatedAt: new Date("2026-07-04"),
  },
]
